### PR TITLE
fix sending max balance

### LINKED ISSUE #750: send tx - max doesnt account for gas price
cannot use the 'max' button

### PR DESCRIPTION
**Pull request by BelfordZ**
merge https://github.com/ETCDEVTeam/emerald-js-ui/pull/64 first, and bump version in package.json

fixes #750 

While this fixes the most obvious issue, there is still something wrong with the gasPrice figure, or a bug in the current version of geth that is causing some tx's to be rejected. Still, though, this is an overall improvement.

### CODE REVIEW

File: src/containers/MultiCreateTransaction/MultiCreateTransaction.js [hunk 1]
```diff
@@ -148,6 +159,7 @@ class MultiCreateTransaction extends React.Component {
             onSubmit={this.onSubmitCreateTransaction}
             onCancel={this.props.onCancel}
             onEmptyAddressBookClick={this.props.onEmptyAddressBookClick}
+          onMaxClicked={this.onMaxClicked}
```
Comment (BelfordZ) [inline src/containers/MultiCreateTransaction/MultiCreateTransaction.js]: fix the indenting

File: package.json [hunk 2]
```diff
@@ -67,7 +67,7 @@
     "electron-log": "^2.2.6",
     "electron-store": "^1.1.0",
     "emerald-js": "git+https://github.com/ETCDEVTeam/emerald-js.git#v0.1.6",
-    "emerald-js-ui": "git+https://github.com/ETCDEVTeam/emerald-js-ui.git#v0.0.29",
+    "emerald-js-ui": "git+https://github.com/ETCDEVTeam/emerald-js-ui.git#fix/create-tx-max",
```
Comment (shanejonas) [inline package.json]: update version
